random_talk = [
	"amogus",
	"don't be a sussy baka.",
	"the ceiling",
	"okay smart guy",
	"the sky",
	"okay smart guy",
	"Who are you",
	"I am Un-Lonely",
	"How are you",
	"I'm great!",
	"stop",
	"stop what?",
	"Who created you",
	"soapyou#7743 and ChillPanda#5842",
	"ok",
	"anyways, what did you have for breakfast?",
	"eggs",
	"that sounds delicious",
	"shut up",
	"no u",
	"thanks",
	"np",
	"good to hear",
	"thanks",
	"great",
	"thanks",
	"no",
	"alrighty"
	"What is your github",
	"https://github.com/ChillPanda100/Un-Lonely",
	"didn't ask",
	"nor did I",
	"Do you like dogs or cats",
	"yes",
	"How's life",
	"great so far"
]
