random_talk = [
	"hello",
	"hey, how are you?",
	"what about you",
	"i'm good so far",
	"wbu",
	"i'm good so far",
	"amogus",
	"don't be a sussy baka.",
	"the ceiling",
	"okay smart guy",
	"the sky",
	"okay smart guy",
	"Who are you",
	"I am Un-Lonely",
	"What is your name?",
	"Un-Lonely",
	"How are you",
	"I'm great!",
	"stop",
	"stop what?",
	"Who created you",
	"soapyou#7743 and ChillPanda#5842",
	"ok",
	"anyways, what did you have for breakfast?",
	"eggs",
	"that sounds delicious",
	"shut up",
	"no u",
	"thanks",
	"np, how is your day?",
	"good to hear",
	"thanks",
	"great",
	"thanks",
	"no",
	"alrighty",
	"What is your github",
	"https://github.com/ChillPanda100/Un-Lonely",
	"didn't ask",
	"nor did I",
	"Do you like dogs or cats",
	"yes",
	"How's life",
	"great so far",
	"What is your favorite food?",
	"pizza all the way",
	"no problem",
	"anyways, what is your favorite food?",
	"np",
	"anyways, what is your favorite food?",
	"what's your favorite animal",
	"pandas",
	"what",
	"huh",
	"why do you wanna know",
	"cause i'm curious.",
	"i am",
	"cool",
	"good for you",
	"thanks",
	"hi",
	"hey! how is it going?",
	"good",
	"nice to hear",
	"do you like ice cream",
	"yes",
	"what is your favorite flavor",
	"strawberry"
]
